import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFF' },
  heroSection: { backgroundColor: '#B71C1C', paddingBottom: 25, paddingTop: 25 },
  centerItems: { alignItems: 'center', marginTop: 15 },
  badge: { backgroundColor: '#FF9100', color: '#FFF', paddingHorizontal: 12, paddingVertical: 4, borderRadius: 12, fontSize: 11, fontWeight: 'bold' },
  mainTitle: { color: '#FFF', fontSize: 36, fontWeight: 'bold', marginTop: 5 },
  subTitle: { color: '#FFF', fontSize: 15, marginTop: 2, marginBottom: 15 },
  whiteBtn: { backgroundColor: '#FFF', paddingVertical: 10, paddingHorizontal: 45, borderRadius: 8, marginBottom: 10 },
  redBtnText: { color: '#B71C1C', fontWeight: 'bold' },
  outlineBtn: { borderWidth: 1, borderColor: '#FFF', paddingVertical: 10, paddingHorizontal: 35, borderRadius: 8 },
  whiteText: { color: '#FFF', fontWeight: 'bold' },
  heroImage: { width: width * 0.9, height: 200, resizeMode: 'contain', marginTop: 15 },
  basePadding: { padding: 15 },
  featureCard: { backgroundColor: '#FFF', borderWidth: 1, borderColor: '#EEE', borderRadius: 12, padding: 15, marginBottom: 20 },
  gridContainer: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 15 },
  gridItem: { alignItems: 'center', width: '48%' },
  featureTitle: { fontSize: 12, fontWeight: 'bold', color: '#000', marginTop: 5, textAlign: 'center' },
  featureSub: { fontSize: 10, color: '#666', textAlign: 'center' },
  sectionDivider: { color: '#B71C1C', textAlign: 'center', fontSize: 12, fontWeight: 'bold' },
  darkHeading: { fontSize: 22, fontWeight: 'bold', color: '#111', textAlign: 'center', marginTop: 5, marginBottom: 15 },
  categoryGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  catBox: { width: '48%', backgroundColor: '#FFF', borderWidth: 1, borderColor: '#F0F0F0', borderRadius: 12, padding: 10, alignItems: 'center', marginBottom: 15 },
  catImage: { width: 90, height: 70, resizeMode: 'contain' },
  catText: { fontSize: 11, fontWeight: 'bold', color: '#333', marginTop: 5, textAlign: 'center' },
  viewAllBtn: { backgroundColor: '#B71C1C', paddingVertical: 12, borderRadius: 25, alignItems: 'center', marginVertical: 10 },
  viewAllText: { color: '#FFF', fontWeight: 'bold', fontSize: 14 },
  productRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 15 },
  productCard: { width: '48%', backgroundColor: '#FFF', borderWidth: 1, borderColor: '#EEE', borderRadius: 12, padding: 10 },
  prodImage: { width: '100%', height: 100, borderRadius: 8, resizeMode: 'cover' },
  prodTitle: { fontSize: 13, fontWeight: 'bold', color: '#222', marginTop: 8 },
  prodWeight: { fontSize: 11, color: '#777', marginTop: 2 },
  priceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 },
  prodPrice: { fontSize: 14, fontWeight: 'bold', color: '#000' },
  addBtn: { borderWidth: 1, borderColor: '#B71C1C', paddingHorizontal: 15, paddingVertical: 4, borderRadius: 6 },
  addText: { color: '#B71C1C', fontWeight: 'bold', fontSize: 12 },
  comingSoonBadge: { backgroundColor: '#FEF2F2', paddingVertical: 6, borderRadius: 6, alignItems: 'center', marginTop: 8, borderWidth: 1, borderColor: '#FEE2E2', width: '100%' },
  comingSoonText: { color: '#B71C1C', fontSize: 12, fontWeight: 'bold' },
  b2bContainer: { backgroundColor: '#111', padding: 25, marginTop: 15, alignItems: 'center' },
  b2bTag: { color: '#FF8A80', fontSize: 11, fontWeight: 'bold' },
  b2bHeading: { color: '#FFF', fontSize: 22, fontWeight: 'bold', marginTop: 5 },
  b2bSub: { color: '#AAA', fontSize: 13, textAlign: 'center', marginTop: 5, marginBottom: 15 },
  b2bButton: { backgroundColor: '#FFF', paddingVertical: 12, paddingHorizontal: 30, borderRadius: 8 },
  b2bButtonText: { color: '#111', fontWeight: 'bold' },
});